### ISSUE TITLE
Error "Symbol '__start' not found" with my asm code

### ISSUE THREAD

**Issue by stagbar** [alexfru/SmallerC#54] opened 2024-08-06 10:52 UTC
I use nasm to compile "demo.asm" to "demo.o"
then I try "smlrl -tiny demo.o -o demo.com"
and I get the Error "Symbol '__start' not found"

**Comment by alexfru** [comment] 2024-08-07 01:09
Duplicate of https://github.com/alexfru/SmallerC/issues/37 or https://github.com/alexfru/SmallerC/issues/17?

**Comment by stagbar** [comment] 2024-08-07 01:31
ok
I fixed my code
`section .text
	global	__start
__start:
	ret
`
It's working,thank

**Closed** 2024-08-07 01:31 UTC
